# gitrepo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: raven-repo
  namespace: flux-system
spec:
  interval: 1m # check every minute
  url: https://github.com/nwrner/raven
  ref:
    branch: main