apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello-app
  namespace: hello
spec:
  interval: 1m
  releaseName: hello-app
  chart:
    spec:
      chart: ./hello-chart
      sourceRef:
        kind: GitRepository
        name: raven-repo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 3
    service:
      type: ClusterIP
      port: 8080